document.write("<div class=\"topnav\" id='nav_bar'>");
document.write("    <div class ='rotate'>");
document.write("  <a href=\"index.html\" class='split'>Andy Sansness<\/a>");
document.write("  <\/div>");
document.write("  <a href=\"reviewcommendations\">Reviewcommendations<\/a>");
document.write("  <a href='puns'>Cartoons<\/a>");
document.write("  <a href=\"wordsmithery\">Wordsmithery<\/a>");
document.write("  <a href=\"articles\">Articles<\/a>");
document.write("  <a href=\"javascript:void(0);\" class=\"icon\" onclick=\"myFunction()\">");
document.write("    <i class=\"fa fa-bars\"><\/i>");
document.write("  <\/a> ");
document.write("      <div class ='shape'><\/div>");
document.write("<\/div>");
document.write("");
document.write("<div class=\"cursor\">");
document.write("  <div class=\"ball big\">");
document.write("    <svg height=\"50\" width=\"50\">");
document.write("      <circle cx=\"25\" cy=\"25\" r=\"20\" stroke-width=\"0\" style='fill: #cce6ff; opacity: 70%;'><\/circle>");
document.write("    <\/svg>");
document.write("  <\/div>");
document.write("  ");
document.write("  <div class=\"ball small\">");
document.write("    <svg height=\"10\" width=\"10\">");
document.write("      <circle cx=\"5\" cy=\"5\" r=\"4\" stroke-width=\"0\" style='fill: #004d99;'><\/circle>");
document.write("    <\/svg>");
document.write("  <\/div>");
document.write("<\/div>");